// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlaygroundGuide.Api.Data;

#nullable disable

namespace PlaygroundGuide.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616222323_AddSubmittedByUserId")]
    partial class AddSubmittedByUserId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlaygroundGuide.Api.Models.Playground", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsHidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("OsmNodeId")
                        .HasColumnType("bigint");

                    b.Property<string>("OsmTags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SubmittedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("OsmNodeId")
                        .IsUnique();

                    b.HasIndex("SubmittedByUserId");

                    b.ToTable("playgrounds", (string)null);
                });

            modelBuilder.Entity("PlaygroundGuide.Api.Models.PlaygroundEnrichment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string[]>("AgeSuitability")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string[]>("Equipment")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OtherEquipment")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PlaygroundId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Reviewed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<string>("TransportInfo")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("PlaygroundId", "UserId")
                        .IsUnique();

                    b.ToTable("playground_enrichments", (string)null);
                });

            modelBuilder.Entity("PlaygroundGuide.Api.Models.PlaygroundFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FlagType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlaygroundId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Other");

                    b.Property<string>("ReasonNote")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("PlaygroundId", "UserId")
                        .IsUnique();

                    b.ToTable("playground_flags", (string)null);
                });

            modelBuilder.Entity("PlaygroundGuide.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a5b-8c7d-9e0f1a2b3c4d"),
                            Name = "Kristine"
                        });
                });

            modelBuilder.Entity("PlaygroundGuide.Api.Models.UserFavourite", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlaygroundId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "PlaygroundId");

                    b.HasIndex("PlaygroundId");

                    b.ToTable("user_favourites", (string)null);
                });

            modelBuilder.Entity("PlaygroundGuide.Api.Models.UserHiddenPlayground", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlaygroundId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "PlaygroundId");

                    b.HasIndex("PlaygroundId");

                    b.ToTable("user_hidden_playgrounds", (string)null);
                });

            modelBuilder.Entity("PlaygroundGuide.Api.Models.UserSaved", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlaygroundId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "PlaygroundId");

                    b.HasIndex("PlaygroundId");

                    b.ToTable("user_saved", (string)null);
                });

            modelBuilder.Entity("PlaygroundGuide.Api.Models.Playground", b =>
                {
                    b.HasOne("PlaygroundGuide.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PlaygroundGuide.Api.Models.PlaygroundEnrichment", b =>
                {
                    b.HasOne("PlaygroundGuide.Api.Models.Playground", "Playground")
                        .WithMany("Enrichments")
                        .HasForeignKey("PlaygroundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlaygroundGuide.Api.Models.User", "User")
                        .WithMany("Enrichments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Playground");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlaygroundGuide.Api.Models.PlaygroundFlag", b =>
                {
                    b.HasOne("PlaygroundGuide.Api.Models.Playground", "Playground")
                        .WithMany("Flags")
                        .HasForeignKey("PlaygroundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlaygroundGuide.Api.Models.User", "User")
                        .WithMany("Flags")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Playground");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlaygroundGuide.Api.Models.UserFavourite", b =>
                {
                    b.HasOne("PlaygroundGuide.Api.Models.Playground", "Playground")
                        .WithMany("Favourites")
                        .HasForeignKey("PlaygroundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlaygroundGuide.Api.Models.User", "User")
                        .WithMany("Favourites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Playground");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlaygroundGuide.Api.Models.UserHiddenPlayground", b =>
                {
                    b.HasOne("PlaygroundGuide.Api.Models.Playground", "Playground")
                        .WithMany("HiddenByUsers")
                        .HasForeignKey("PlaygroundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlaygroundGuide.Api.Models.User", "User")
                        .WithMany("Hidden")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Playground");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlaygroundGuide.Api.Models.UserSaved", b =>
                {
                    b.HasOne("PlaygroundGuide.Api.Models.Playground", "Playground")
                        .WithMany("Saved")
                        .HasForeignKey("PlaygroundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlaygroundGuide.Api.Models.User", "User")
                        .WithMany("Saved")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Playground");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlaygroundGuide.Api.Models.Playground", b =>
                {
                    b.Navigation("Enrichments");

                    b.Navigation("Favourites");

                    b.Navigation("Flags");

                    b.Navigation("HiddenByUsers");

                    b.Navigation("Saved");
                });

            modelBuilder.Entity("PlaygroundGuide.Api.Models.User", b =>
                {
                    b.Navigation("Enrichments");

                    b.Navigation("Favourites");

                    b.Navigation("Flags");

                    b.Navigation("Hidden");

                    b.Navigation("Saved");
                });
#pragma warning restore 612, 618
        }
    }
}
