// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlaygroundGuide.Api.Data;

#nullable disable

namespace PlaygroundGuide.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlaygroundGuide.Api.Models.Playground", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("OsmNodeId")
                        .HasColumnType("bigint");

                    b.Property<string>("OsmTags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("OsmNodeId")
                        .IsUnique();

                    b.ToTable("playgrounds", (string)null);
                });

            modelBuilder.Entity("PlaygroundGuide.Api.Models.PlaygroundEnrichment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string[]>("AgeSuitability")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string[]>("Equipment")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OtherEquipment")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PlaygroundId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Reviewed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<string>("TransportInfo")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("PlaygroundId", "UserId")
                        .IsUnique();

                    b.ToTable("playground_enrichments", (string)null);
                });

            modelBuilder.Entity("PlaygroundGuide.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a5b-8c7d-9e0f1a2b3c4d"),
                            Name = "Kristine"
                        });
                });

            modelBuilder.Entity("PlaygroundGuide.Api.Models.PlaygroundEnrichment", b =>
                {
                    b.HasOne("PlaygroundGuide.Api.Models.Playground", "Playground")
                        .WithMany("Enrichments")
                        .HasForeignKey("PlaygroundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlaygroundGuide.Api.Models.User", "User")
                        .WithMany("Enrichments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Playground");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlaygroundGuide.Api.Models.Playground", b =>
                {
                    b.Navigation("Enrichments");
                });

            modelBuilder.Entity("PlaygroundGuide.Api.Models.User", b =>
                {
                    b.Navigation("Enrichments");
                });
#pragma warning restore 612, 618
        }
    }
}
