// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlaygroundGuide.Api.Data;

#nullable disable

namespace PlaygroundGuide.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlaygroundGuide.Api.Models.Playground", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("OsmNodeId")
                        .HasColumnType("bigint");

                    b.Property<string>("OsmTags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("OsmNodeId")
                        .IsUnique();

                    b.ToTable("playgrounds", (string)null);
                });

            modelBuilder.Entity("PlaygroundGuide.Api.Models.PlaygroundEnrichment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("Equipment")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Parking")
                        .HasColumnType("text");

                    b.Property<Guid>("PlaygroundId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Reviewed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("PlaygroundId");

                    b.ToTable("playground_enrichments", (string)null);
                });

            modelBuilder.Entity("PlaygroundGuide.Api.Models.PlaygroundEnrichment", b =>
                {
                    b.HasOne("PlaygroundGuide.Api.Models.Playground", "Playground")
                        .WithMany("Enrichments")
                        .HasForeignKey("PlaygroundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Playground");
                });

            modelBuilder.Entity("PlaygroundGuide.Api.Models.Playground", b =>
                {
                    b.Navigation("Enrichments");
                });
#pragma warning restore 612, 618
        }
    }
}
